version: "2.1"
services:
  server:
    image: jetbrains/teamcity-server:latest-nanoserver
    ports:
      - "8111:8111"
    volumes:
      - ./teamcity-server\data:C:\ProgramData\JetBrains\TeamCity
      - ./teamcity-server\logs:C:\TeamCity\logs
    mem_limit: 2g
  agent01:
    image: jetbrains/teamcity-agent:latest-nanoserver
    environment:
      - AGENT_NAME=Agent01
      - SERVER_URL=http://server:8111
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:ReservedCodeCacheSize=350m
    volumes:
      - .\teamcity-agent01\conf:C:\BuildAgent\conf
      - .\teamcity-agent01\work:C:\BuildAgent\work
  agent02:
    image: tc-agent:latest
    environment:
      - AGENT_NAME=Agent02
      - SERVER_URL=http://server:8111
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:ReservedCodeCacheSize=350m
    volumes:
      - .\teamcity-agent02\conf:C:\BuildAgent\conf
      - .\teamcity-agent02\work:C:\BuildAgent\work
